import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { resetServerContext } from "react-beautiful-dnd";
import { AddItem } from "../components/AddItem";
import { DraggableContainer } from "../components/DraggableContainer";
import { Menu } from "../components/Menu";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  resetServerContext();
  const [shouldReload, setShouldReload] = useState(false);
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [isRemoveActive, setIsRemoveActive] = useState(false);

  const handleReload = () => {
    setShouldReload(!shouldReload);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DraggableContainer
          onRemove={() => setIsRemoveActive(false)}
          isRemoveActive={isRemoveActive}
          shouldReload={shouldReload}
        />
        <Menu
          onAdd={() => setIsAddModalOpen(true)}
          onRemove={() => setIsRemoveActive(true)}
          onReload={handleReload}
        ></Menu>
        <AddItem
          onReload={handleReload}
          onClose={() => setIsAddModalOpen(false)}
          isOpen={isAddModalOpen}
        ></AddItem>
      </main>
    </div>
  );
};

export default Home;
