import type { NextPage } from "next";
import Head from "next/head";
import { resetServerContext } from "react-beautiful-dnd";
import { DraggableContainer } from "../components/DraggableContainer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  resetServerContext();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DraggableContainer />
      </main>
    </div>
  );
};

export default Home;
